# permissions for end users to edit kubeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeconfig-editor-role
rules:
- apiGroups:
  - manager.sukai.io
  resources:
  - kubeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manager.sukai.io
  resources:
  - kubeconfigs/status
  verbs:
  - get
